### ISSUE TITLE
Pre Release Checklist

### ISSUE THREAD

**Issue by arjun-rao** [4and4/MiloServer#75]
### Release Checklist 

- [x] Remove debug tab
- [ ] Clear console logs
- [ ] Add help menu
